version: 2.1


orbs:
  browser-tools: circleci/browser-tools@1.1
jobs:
  build: 
    docker:
      - image: cimg/ruby:2.7-browsers
    steps:
      - browser-tools/install-browser-tools
      - checkout
      - run: ruby --version
      - run: node --version
      - run: google-chrome --version
      - run:
          name: install dependencies
          command: sudo npm install bower -g
      - run:
          name: install dependencies
          command: sudo npm install grunt -g
      - run:
          name: install dependencies
          command: bower install
      - run:
          name: install dependencies
          command: npm install
      - run:
          name: install dependencies
          command: gem update --system
      - run:
          name: install dependencies
          command: gem install compass
      - run:
          name: install dependencies
          command: gem install sass
      - run:
          name: run tests
          command: grunt test
      - run:
          name: Build
          command: grunt build

workflows:
  version: 2.1
  build-and-test:
    jobs:
      - build
